<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\InternalCategory;
use App\Models\InternalBrand;
use App\Models\InternalLocation;
use App\Models\InternalAsset;

class InternalInventorySeeder extends Seeder
{
    public function run(): void
    {
        // Categories for IT Company
        $categories = [
            ['name' => 'Fiber Optic Equipment', 'description' => 'Splicing machines, OTDR, power meters, and fiber tools'],
            ['name' => 'Computer & Laptop', 'description' => 'Desktop computers, laptops, and workstations'],
            ['name' => 'Networking Equipment', 'description' => 'Routers, switches, access points, and network tools'],
            ['name' => 'Testing Equipment', 'description' => 'Cable testers, multimeters, and diagnostic tools'],
            ['name' => 'Power Equipment', 'description' => 'UPS, power banks, generators, and power tools'],
            ['name' => 'Communication Devices', 'description' => 'Walkie-talkies, phones, and communication equipment'],
            ['name' => 'Safety Equipment', 'description' => 'Safety gear, PPE, and protective equipment'],
            ['name' => 'Hand Tools', 'description' => 'Screwdrivers, pliers, crimping tools, and general tools'],
            ['name' => 'Vehicles', 'description' => 'Company vehicles for site visits'],
            ['name' => 'Office Equipment', 'description' => 'Projectors, printers, and office devices'],
        ];

        foreach ($categories as $cat) {
            InternalCategory::create($cat);
        }

        // Brands for IT Equipment
        $brands = [
            ['name' => 'Fujikura', 'description' => 'Japanese fiber optic equipment manufacturer'],
            ['name' => 'EXFO', 'description' => 'Test and measurement equipment for telecom'],
            ['name' => 'Fluke Networks', 'description' => 'Network testing and cable certification'],
            ['name' => 'Dell', 'description' => 'Computer and laptop manufacturer'],
            ['name' => 'HP', 'description' => 'Hewlett-Packard computers and printers'],
            ['name' => 'Lenovo', 'description' => 'ThinkPad and computer manufacturer'],
            ['name' => 'Cisco', 'description' => 'Networking equipment manufacturer'],
            ['name' => 'TP-Link', 'description' => 'Networking and WiFi equipment'],
            ['name' => 'Ubiquiti', 'description' => 'Enterprise networking solutions'],
            ['name' => 'APC', 'description' => 'UPS and power protection'],
            ['name' => 'Anritsu', 'description' => 'Test and measurement instruments'],
            ['name' => 'JDSU/Viavi', 'description' => 'Fiber optic test equipment'],
            ['name' => 'Sumitomo', 'description' => 'Fiber optic fusion splicers'],
            ['name' => 'Motorola', 'description' => 'Communication devices'],
            ['name' => 'Toyota', 'description' => 'Vehicle manufacturer'],
            ['name' => 'Proton', 'description' => 'Malaysian vehicle manufacturer'],
            ['name' => 'Epson', 'description' => 'Printers and projectors'],
            ['name' => 'Apple', 'description' => 'MacBook and Apple devices'],
            ['name' => 'ASUS', 'description' => 'Laptops and computer components'],
            ['name' => 'Hioki', 'description' => 'Electrical measuring instruments'],
        ];

        foreach ($brands as $brand) {
            InternalBrand::create($brand);
        }

        // Locations
        $locations = [
            ['name' => 'Main Office - Store Room', 'description' => 'Main storage room at HQ'],
            ['name' => 'Main Office - IT Room', 'description' => 'IT department equipment room'],
            ['name' => 'Main Office - Reception', 'description' => 'Front desk area'],
            ['name' => 'Warehouse A', 'description' => 'Main warehouse for large equipment'],
            ['name' => 'Warehouse B', 'description' => 'Secondary warehouse'],
            ['name' => 'Vehicle Bay', 'description' => 'Company vehicle parking'],
            ['name' => 'Field Team 1', 'description' => 'Assigned to field team 1'],
            ['name' => 'Field Team 2', 'description' => 'Assigned to field team 2'],
            ['name' => 'Meeting Room 1', 'description' => 'Conference room equipment'],
            ['name' => 'Server Room', 'description' => 'Data center and server equipment'],
        ];

        foreach ($locations as $loc) {
            InternalLocation::create($loc);
        }

        // Get IDs for reference
        $catIds = InternalCategory::pluck('id', 'name');
        $brandIds = InternalBrand::pluck('id', 'name');
        $locIds = InternalLocation::pluck('id', 'name');

        // Assets
        $assets = [
            // Fiber Optic Equipment
            [
                'asset_tag' => 'INT-FO-001',
                'name' => 'Fusion Splicer Machine',
                'category_id' => $catIds['Fiber Optic Equipment'],
                'brand_id' => $brandIds['Fujikura'],
                'model' => 'FSM-90S+',
                'serial_number' => 'FUJ90S2024001',
                'location_id' => $locIds['Main Office - Store Room'],
                'condition' => 'excellent',
                'purchase_price' => 45000.00,
                'purchase_date' => '2024-03-15',
                'warranty_expiry' => '2027-03-15',
                'notes' => 'Primary fusion splicer for fiber projects',
            ],
            [
                'asset_tag' => 'INT-FO-002',
                'name' => 'Fusion Splicer Machine',
                'category_id' => $catIds['Fiber Optic Equipment'],
                'brand_id' => $brandIds['Sumitomo'],
                'model' => 'T-602S',
                'serial_number' => 'SUM602S2023045',
                'location_id' => $locIds['Warehouse A'],
                'condition' => 'good',
                'purchase_price' => 38000.00,
                'purchase_date' => '2023-08-20',
                'warranty_expiry' => '2026-08-20',
                'notes' => 'Backup fusion splicer',
            ],
            [
                'asset_tag' => 'INT-FO-003',
                'name' => 'OTDR (Optical Time Domain Reflectometer)',
                'category_id' => $catIds['Fiber Optic Equipment'],
                'brand_id' => $brandIds['EXFO'],
                'model' => 'MaxTester 730C',
                'serial_number' => 'EXFO730C2024012',
                'location_id' => $locIds['Main Office - Store Room'],
                'condition' => 'excellent',
                'purchase_price' => 28000.00,
                'purchase_date' => '2024-01-10',
                'warranty_expiry' => '2027-01-10',
                'notes' => 'For fiber testing and fault location',
            ],
            [
                'asset_tag' => 'INT-FO-004',
                'name' => 'Optical Power Meter',
                'category_id' => $catIds['Fiber Optic Equipment'],
                'brand_id' => $brandIds['JDSU/Viavi'],
                'model' => 'OLP-85',
                'serial_number' => 'VIAVI85P2023089',
                'location_id' => $locIds['Field Team 1'],
                'condition' => 'good',
                'purchase_price' => 3500.00,
                'purchase_date' => '2023-06-15',
                'warranty_expiry' => '2025-06-15',
                'notes' => 'Handheld power meter',
            ],
            [
                'asset_tag' => 'INT-FO-005',
                'name' => 'Visual Fault Locator',
                'category_id' => $catIds['Fiber Optic Equipment'],
                'brand_id' => $brandIds['EXFO'],
                'model' => 'FLS-240',
                'serial_number' => 'EXFOVFL2024033',
                'location_id' => $locIds['Field Team 2'],
                'condition' => 'excellent',
                'purchase_price' => 1200.00,
                'purchase_date' => '2024-02-28',
                'warranty_expiry' => '2026-02-28',
                'notes' => 'Red laser VFL for fiber breaks',
            ],

            // Computers & Laptops
            [
                'asset_tag' => 'INT-PC-001',
                'name' => 'Desktop Computer',
                'category_id' => $catIds['Computer & Laptop'],
                'brand_id' => $brandIds['Dell'],
                'model' => 'OptiPlex 7090',
                'serial_number' => 'DELL7090SVC001',
                'location_id' => $locIds['Main Office - IT Room'],
                'condition' => 'excellent',
                'purchase_price' => 4500.00,
                'purchase_date' => '2024-01-05',
                'warranty_expiry' => '2027-01-05',
                'notes' => 'Admin workstation',
            ],
            [
                'asset_tag' => 'INT-PC-002',
                'name' => 'Desktop Computer',
                'category_id' => $catIds['Computer & Laptop'],
                'brand_id' => $brandIds['HP'],
                'model' => 'ProDesk 400 G7',
                'serial_number' => 'HP400G7SVC002',
                'location_id' => $locIds['Main Office - Reception'],
                'condition' => 'good',
                'purchase_price' => 3800.00,
                'purchase_date' => '2023-09-12',
                'warranty_expiry' => '2026-09-12',
                'notes' => 'Reception counter PC',
            ],
            [
                'asset_tag' => 'INT-LT-001',
                'name' => 'Laptop ThinkPad',
                'category_id' => $catIds['Computer & Laptop'],
                'brand_id' => $brandIds['Lenovo'],
                'model' => 'ThinkPad T14 Gen 3',
                'serial_number' => 'LENT14G3001',
                'location_id' => $locIds['Main Office - Store Room'],
                'condition' => 'excellent',
                'purchase_price' => 5200.00,
                'purchase_date' => '2024-02-20',
                'warranty_expiry' => '2027-02-20',
                'notes' => 'For site engineers',
            ],
            [
                'asset_tag' => 'INT-LT-002',
                'name' => 'Laptop ThinkPad',
                'category_id' => $catIds['Computer & Laptop'],
                'brand_id' => $brandIds['Lenovo'],
                'model' => 'ThinkPad T14 Gen 3',
                'serial_number' => 'LENT14G3002',
                'location_id' => $locIds['Main Office - Store Room'],
                'condition' => 'excellent',
                'purchase_price' => 5200.00,
                'purchase_date' => '2024-02-20',
                'warranty_expiry' => '2027-02-20',
                'notes' => 'For site engineers',
            ],
            [
                'asset_tag' => 'INT-LT-003',
                'name' => 'MacBook Pro',
                'category_id' => $catIds['Computer & Laptop'],
                'brand_id' => $brandIds['Apple'],
                'model' => 'MacBook Pro 14" M3',
                'serial_number' => 'APPMBP14M3001',
                'location_id' => $locIds['Main Office - IT Room'],
                'condition' => 'excellent',
                'purchase_price' => 9500.00,
                'purchase_date' => '2024-06-01',
                'warranty_expiry' => '2026-06-01',
                'notes' => 'Design and development work',
            ],
            [
                'asset_tag' => 'INT-LT-004',
                'name' => 'Gaming Laptop',
                'category_id' => $catIds['Computer & Laptop'],
                'brand_id' => $brandIds['ASUS'],
                'model' => 'ROG Strix G16',
                'serial_number' => 'ASUSROG16001',
                'location_id' => $locIds['Main Office - Store Room'],
                'condition' => 'good',
                'purchase_price' => 6800.00,
                'purchase_date' => '2023-11-15',
                'warranty_expiry' => '2025-11-15',
                'notes' => 'High performance for CAD work',
            ],

            // Networking Equipment
            [
                'asset_tag' => 'INT-NW-001',
                'name' => 'Managed Switch 48-Port',
                'category_id' => $catIds['Networking Equipment'],
                'brand_id' => $brandIds['Cisco'],
                'model' => 'Catalyst 9200-48P',
                'serial_number' => 'CISCO9200P001',
                'location_id' => $locIds['Server Room'],
                'condition' => 'excellent',
                'purchase_price' => 12000.00,
                'purchase_date' => '2024-01-20',
                'warranty_expiry' => '2027-01-20',
                'notes' => 'Main office switch with PoE',
            ],
            [
                'asset_tag' => 'INT-NW-002',
                'name' => 'Wireless Access Point',
                'category_id' => $catIds['Networking Equipment'],
                'brand_id' => $brandIds['Ubiquiti'],
                'model' => 'UniFi U6 Pro',
                'serial_number' => 'UBIU6PRO001',
                'location_id' => $locIds['Main Office - IT Room'],
                'condition' => 'excellent',
                'purchase_price' => 850.00,
                'purchase_date' => '2024-03-10',
                'warranty_expiry' => '2026-03-10',
                'notes' => 'WiFi 6 access point',
            ],
            [
                'asset_tag' => 'INT-NW-003',
                'name' => 'Wireless Access Point',
                'category_id' => $catIds['Networking Equipment'],
                'brand_id' => $brandIds['Ubiquiti'],
                'model' => 'UniFi U6 Pro',
                'serial_number' => 'UBIU6PRO002',
                'location_id' => $locIds['Meeting Room 1'],
                'condition' => 'excellent',
                'purchase_price' => 850.00,
                'purchase_date' => '2024-03-10',
                'warranty_expiry' => '2026-03-10',
                'notes' => 'WiFi 6 access point',
            ],
            [
                'asset_tag' => 'INT-NW-004',
                'name' => 'Router',
                'category_id' => $catIds['Networking Equipment'],
                'brand_id' => $brandIds['TP-Link'],
                'model' => 'ER7206 Omada',
                'serial_number' => 'TPER7206001',
                'location_id' => $locIds['Server Room'],
                'condition' => 'good',
                'purchase_price' => 1200.00,
                'purchase_date' => '2023-07-15',
                'warranty_expiry' => '2026-07-15',
                'notes' => 'Multi-WAN VPN router',
            ],

            // Testing Equipment
            [
                'asset_tag' => 'INT-TE-001',
                'name' => 'Cable Certifier',
                'category_id' => $catIds['Testing Equipment'],
                'brand_id' => $brandIds['Fluke Networks'],
                'model' => 'DSX-8000',
                'serial_number' => 'FLKDSX8K001',
                'location_id' => $locIds['Main Office - Store Room'],
                'condition' => 'excellent',
                'purchase_price' => 35000.00,
                'purchase_date' => '2024-04-01',
                'warranty_expiry' => '2027-04-01',
                'notes' => 'Cat6A/Cat8 cable certification',
            ],
            [
                'asset_tag' => 'INT-TE-002',
                'name' => 'Network Cable Tester',
                'category_id' => $catIds['Testing Equipment'],
                'brand_id' => $brandIds['Fluke Networks'],
                'model' => 'MicroScanner PoE',
                'serial_number' => 'FLKMSPE001',
                'location_id' => $locIds['Field Team 1'],
                'condition' => 'good',
                'purchase_price' => 2800.00,
                'purchase_date' => '2023-10-20',
                'warranty_expiry' => '2025-10-20',
                'notes' => 'PoE and cable verification',
            ],
            [
                'asset_tag' => 'INT-TE-003',
                'name' => 'Digital Multimeter',
                'category_id' => $catIds['Testing Equipment'],
                'brand_id' => $brandIds['Hioki'],
                'model' => 'DT4282',
                'serial_number' => 'HIOKIDT4282001',
                'location_id' => $locIds['Main Office - Store Room'],
                'condition' => 'excellent',
                'purchase_price' => 1500.00,
                'purchase_date' => '2024-02-15',
                'warranty_expiry' => '2027-02-15',
                'notes' => 'True RMS digital multimeter',
            ],

            // Power Equipment
            [
                'asset_tag' => 'INT-PW-001',
                'name' => 'UPS 3000VA',
                'category_id' => $catIds['Power Equipment'],
                'brand_id' => $brandIds['APC'],
                'model' => 'Smart-UPS 3000',
                'serial_number' => 'APCSMT3K001',
                'location_id' => $locIds['Server Room'],
                'condition' => 'excellent',
                'purchase_price' => 8500.00,
                'purchase_date' => '2024-01-15',
                'warranty_expiry' => '2027-01-15',
                'notes' => 'Server room backup power',
            ],
            [
                'asset_tag' => 'INT-PW-002',
                'name' => 'UPS 1500VA',
                'category_id' => $catIds['Power Equipment'],
                'brand_id' => $brandIds['APC'],
                'model' => 'Back-UPS Pro 1500',
                'serial_number' => 'APCBUP1500001',
                'location_id' => $locIds['Main Office - IT Room'],
                'condition' => 'good',
                'purchase_price' => 1800.00,
                'purchase_date' => '2023-06-20',
                'warranty_expiry' => '2025-06-20',
                'notes' => 'Workstation backup power',
            ],
            [
                'asset_tag' => 'INT-PW-003',
                'name' => 'Portable Power Station',
                'category_id' => $catIds['Power Equipment'],
                'brand_id' => $brandIds['APC'],
                'model' => 'PowerStack 1000',
                'serial_number' => 'APCPS1000001',
                'location_id' => $locIds['Main Office - Store Room'],
                'condition' => 'excellent',
                'purchase_price' => 3200.00,
                'purchase_date' => '2024-05-10',
                'warranty_expiry' => '2026-05-10',
                'notes' => 'For field work power supply',
            ],

            // Communication Devices
            [
                'asset_tag' => 'INT-CM-001',
                'name' => 'Walkie Talkie Set',
                'category_id' => $catIds['Communication Devices'],
                'brand_id' => $brandIds['Motorola'],
                'model' => 'T82 Extreme',
                'serial_number' => 'MOTT82E001',
                'location_id' => $locIds['Main Office - Store Room'],
                'condition' => 'good',
                'purchase_price' => 650.00,
                'purchase_date' => '2023-08-15',
                'warranty_expiry' => '2025-08-15',
                'notes' => 'Set of 4 units for site work',
            ],
            [
                'asset_tag' => 'INT-CM-002',
                'name' => 'Walkie Talkie Set',
                'category_id' => $catIds['Communication Devices'],
                'brand_id' => $brandIds['Motorola'],
                'model' => 'T82 Extreme',
                'serial_number' => 'MOTT82E002',
                'location_id' => $locIds['Field Team 1'],
                'condition' => 'good',
                'purchase_price' => 650.00,
                'purchase_date' => '2023-08-15',
                'warranty_expiry' => '2025-08-15',
                'notes' => 'Set of 4 units for site work',
            ],

            // Safety Equipment
            [
                'asset_tag' => 'INT-SF-001',
                'name' => 'Safety Helmet Set',
                'category_id' => $catIds['Safety Equipment'],
                'brand_id' => null,
                'model' => 'Industrial Grade',
                'serial_number' => null,
                'location_id' => $locIds['Main Office - Store Room'],
                'condition' => 'good',
                'purchase_price' => 450.00,
                'purchase_date' => '2024-01-10',
                'warranty_expiry' => null,
                'notes' => 'Set of 10 helmets',
            ],
            [
                'asset_tag' => 'INT-SF-002',
                'name' => 'Safety Vest Set',
                'category_id' => $catIds['Safety Equipment'],
                'brand_id' => null,
                'model' => 'High Visibility',
                'serial_number' => null,
                'location_id' => $locIds['Main Office - Store Room'],
                'condition' => 'excellent',
                'purchase_price' => 300.00,
                'purchase_date' => '2024-03-01',
                'warranty_expiry' => null,
                'notes' => 'Set of 15 vests',
            ],
            [
                'asset_tag' => 'INT-SF-003',
                'name' => 'First Aid Kit',
                'category_id' => $catIds['Safety Equipment'],
                'brand_id' => null,
                'model' => 'Industrial First Aid',
                'serial_number' => null,
                'location_id' => $locIds['Main Office - Store Room'],
                'condition' => 'excellent',
                'purchase_price' => 250.00,
                'purchase_date' => '2024-06-01',
                'warranty_expiry' => null,
                'notes' => 'Complete first aid kit',
            ],

            // Hand Tools
            [
                'asset_tag' => 'INT-TL-001',
                'name' => 'Fiber Tool Kit',
                'category_id' => $catIds['Hand Tools'],
                'brand_id' => $brandIds['Fujikura'],
                'model' => 'FTK-01',
                'serial_number' => 'FUJFTK01001',
                'location_id' => $locIds['Main Office - Store Room'],
                'condition' => 'excellent',
                'purchase_price' => 2800.00,
                'purchase_date' => '2024-02-01',
                'warranty_expiry' => '2026-02-01',
                'notes' => 'Complete fiber preparation kit',
            ],
            [
                'asset_tag' => 'INT-TL-002',
                'name' => 'Network Tool Kit',
                'category_id' => $catIds['Hand Tools'],
                'brand_id' => $brandIds['Fluke Networks'],
                'model' => 'Pro Tool Kit',
                'serial_number' => 'FLKPTK001',
                'location_id' => $locIds['Field Team 1'],
                'condition' => 'good',
                'purchase_price' => 1500.00,
                'purchase_date' => '2023-09-15',
                'warranty_expiry' => '2025-09-15',
                'notes' => 'Crimping, punch down, cable tools',
            ],
            [
                'asset_tag' => 'INT-TL-003',
                'name' => 'Network Tool Kit',
                'category_id' => $catIds['Hand Tools'],
                'brand_id' => $brandIds['Fluke Networks'],
                'model' => 'Pro Tool Kit',
                'serial_number' => 'FLKPTK002',
                'location_id' => $locIds['Field Team 2'],
                'condition' => 'good',
                'purchase_price' => 1500.00,
                'purchase_date' => '2023-09-15',
                'warranty_expiry' => '2025-09-15',
                'notes' => 'Crimping, punch down, cable tools',
            ],

            // Vehicles
            [
                'asset_tag' => 'INT-VH-001',
                'name' => 'Service Van',
                'category_id' => $catIds['Vehicles'],
                'brand_id' => $brandIds['Toyota'],
                'model' => 'Hiace Panel Van',
                'serial_number' => 'WQD1234',
                'location_id' => $locIds['Vehicle Bay'],
                'condition' => 'good',
                'purchase_price' => 125000.00,
                'purchase_date' => '2022-06-15',
                'warranty_expiry' => '2025-06-15',
                'notes' => 'Main service vehicle',
            ],
            [
                'asset_tag' => 'INT-VH-002',
                'name' => 'Service Van',
                'category_id' => $catIds['Vehicles'],
                'brand_id' => $brandIds['Proton'],
                'model' => 'Exora Bold',
                'serial_number' => 'WQE5678',
                'location_id' => $locIds['Vehicle Bay'],
                'condition' => 'good',
                'purchase_price' => 75000.00,
                'purchase_date' => '2023-03-20',
                'warranty_expiry' => '2028-03-20',
                'notes' => 'Secondary service vehicle',
            ],

            // Office Equipment
            [
                'asset_tag' => 'INT-OF-001',
                'name' => 'Projector',
                'category_id' => $catIds['Office Equipment'],
                'brand_id' => $brandIds['Epson'],
                'model' => 'EB-992F',
                'serial_number' => 'EPSEB992F001',
                'location_id' => $locIds['Meeting Room 1'],
                'condition' => 'excellent',
                'purchase_price' => 4500.00,
                'purchase_date' => '2024-01-25',
                'warranty_expiry' => '2027-01-25',
                'notes' => 'Full HD laser projector',
            ],
            [
                'asset_tag' => 'INT-OF-002',
                'name' => 'Multifunction Printer',
                'category_id' => $catIds['Office Equipment'],
                'brand_id' => $brandIds['HP'],
                'model' => 'LaserJet Pro MFP M428fdw',
                'serial_number' => 'HPM428FDW001',
                'location_id' => $locIds['Main Office - IT Room'],
                'condition' => 'good',
                'purchase_price' => 2200.00,
                'purchase_date' => '2023-05-10',
                'warranty_expiry' => '2025-05-10',
                'notes' => 'Print, scan, copy, fax',
            ],
            [
                'asset_tag' => 'INT-OF-003',
                'name' => 'Label Printer',
                'category_id' => $catIds['Office Equipment'],
                'brand_id' => $brandIds['Epson'],
                'model' => 'LW-C610',
                'serial_number' => 'EPSLWC610001',
                'location_id' => $locIds['Main Office - Store Room'],
                'condition' => 'excellent',
                'purchase_price' => 850.00,
                'purchase_date' => '2024-04-15',
                'warranty_expiry' => '2026-04-15',
                'notes' => 'For cable and asset labeling',
            ],
        ];

        foreach ($assets as $asset) {
            InternalAsset::create(array_merge($asset, ['status' => 'available']));
        }
    }
}
